/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oussama;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Franck
 */
public class Interface extends javax.swing.JFrame  implements ActionListener{

    /**
     * Creates new form Interface
     */
    private int caseChoisie; 
    private Plateau p ;
    private boolean coupsPossibles [][] ;
    private int tab [][]= new int [10][10];
    private JButton button [][]=new JButton[8][8];
    //  private int plateau [][]= new int [10][10];
    private Icon blanc = new ImageIcon("images/blanc.png");
    private Icon noir = new ImageIcon("images/noir.png");
    private Icon img = new ImageIcon("images/isen.png");
    private Icon regles = new ImageIcon("images/regles.gif");
    private Icon coupPossible = new ImageIcon("images/coupPossible.gif");
    int joueur = 1; 
    private int n = 1;
    private int b=2;
    private int vide = 0 ;
    private int nbPions; 
    private String txt;
    private JLabel infoMessage;
    private boolean coupPossibles[][]= new boolean [10][10];
    
    public Interface() {
        initComponents();
    }
    public void affichePlateau(){
        plateau.setLayout(new GridLayout(8,8));
        for(int i=0;i<8;i++){
            for (int j=0;j<8;j++){
                    button[i][j]= new JButton();
                    button[i][j].addActionListener(this);
                    plateau.add(button[i][j]); 
                    button[i][j].setBackground(new Color(0,102,0));
            }
        } 
        for(int i=1;i<9;i++){
            for (int j=1;j<9;j++){
              if(tab[i][j]==2)
                  button[i-1][j-1].setIcon(blanc);
              if (tab[i][j]==1)
                  button[i-1][j-1].setIcon(noir);
            }
        }
       for(int i=1;i<9;i++){
            for (int j=1;j<9;j++){
              if(coupPossibles[i][j])
                  button[i-1][j-1].setIcon(coupPossible);
              
            }
        }
       if(p.partieEstFinie()){
           p.calculScore();
           if(p.getNbPionsBlanc() > p.getNbPionsNoir())
               JOptionPane.showMessageDialog(null,"blanc a gagné","BRAVO",JOptionPane.INFORMATION_MESSAGE);
           else if(p.getNbPionsNoir() > p.getNbPionsBlanc())
               JOptionPane.showMessageDialog(null,"Noir a gagné","BRAVO",JOptionPane.INFORMATION_MESSAGE);
           else 
               JOptionPane.showMessageDialog(null,"Match Nul","faible",JOptionPane.INFORMATION_MESSAGE);
       }
       coupPossibles= new boolean [10][10];
      
    }
	public void afficheScore(){
		ScoreNoir.setText("scoreNoir : "+p.nbPionsNoir);
		ScoreBlanc.setText("scoreBlanc : "+p.nbPionsBlanc);
	}
    public void apropos(){
     JOptionPane.showMessageDialog(null,"OZ+Dani+Arab+mhamed","Made by N2",JOptionPane.INFORMATION_MESSAGE,img);
     } 
     
    /**

     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plateau = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        ScoreNoir = new javax.swing.JLabel();
        ScoreBlanc = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout plateauLayout = new javax.swing.GroupLayout(plateau);
        plateau.setLayout(plateauLayout);
        plateauLayout.setHorizontalGroup(
            plateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        plateauLayout.setVerticalGroup(
            plateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Commencer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ScoreNoir.setText("ScoreNoir");

        ScoreBlanc.setText("ScoreBlanc");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScoreNoir)
                    .addComponent(ScoreBlanc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(plateau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(plateau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(ScoreBlanc)
                        .addGap(53, 53, 53)
                        .addComponent(ScoreNoir)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        p = new  Plateau();
        p.coupsPossibles();
        coupPossibles=p.getCoupsPossibles();
        tab=p.getPlateau();
        affichePlateau(); 
        //JOptionPane.showMessageDialog(null,":)","Règle Du Jeu",JOptionPane.INFORMATION_MESSAGE,regles);
       jButton1.setEnabled(false); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        apropos();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    
   
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ScoreBlanc;
    private javax.swing.JLabel ScoreNoir;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel plateau;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        plateau.removeAll();
        p=new Plateau (tab,joueur);
       
        for(int i = 0;i<8;i++){
              for (int j=0;j<8;j++){
              Object b = e.getSource();
                if(b==button[i][j]&& joueur==1 ){
                    p.jouerUnCoup(i+1,j+1);
                    p.updatePlateau();
                    tab=p.getPlateau();
                    p.coupsPossibles();
                    coupPossibles=p.getCoupsPossibles();
                    affichePlateau();
                    p.afficheCoupPossible();
                    p.afficheScore();
                    afficheScore();
                    joueur=2;
                    
    
                }
                 else if (b==button[i][j]&& joueur==2 ){
                    
                      p.jouerUnCoup(i+1,j+1);
                      p.updatePlateau();
                      tab=p.getPlateau();
                      p.coupsPossibles(); 
                      coupPossibles=p.getCoupsPossibles();
                      p.affichePlateau(); 
                      affichePlateau();    
                      p.afficheCoupPossible();
                      p.afficheScore();
                       afficheScore();
                      joueur=1;
                }
         
            }
        }
    
    }}